"""empty message

Revision ID: 0e6df0bb2be8
Revises: e47b1d354d3e
Create Date: 2024-09-11 17:13:58.619861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6df0bb2be8'
down_revision = 'e47b1d354d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('sent',
               existing_type=sa.DATETIME(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('sent',
               existing_type=sa.Boolean(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
