"""Added default value for sent column in Reminder

Revision ID: e47b1d354d3e
Revises: ed938388735d
Create Date: 2024-09-11 02:33:33.860466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47b1d354d3e'
down_revision = 'ed938388735d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('sent',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('sent',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
