"""Added send_at and send columns to the Reminder model

Revision ID: ed938388735d
Revises: ea339f8ad814
Create Date: 2024-09-11 01:21:44.124265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed938388735d'
down_revision = 'ea339f8ad814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('sent', sa.DateTime(), nullable=False))
        batch_op.drop_column('reminder_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sa.DATETIME(), nullable=False))
        batch_op.drop_column('sent')
        batch_op.drop_column('send_at')

    # ### end Alembic commands ###
